# import os
# import json
# from datetime import datetime
# from fpdf import FPDF
# from typing import List, Dict
# from agents.base_agent import BaseAgent

# class ReportGeneratorAgent(BaseAgent):
#     def __init__(self, context, output_dir: str = "reports"):
#         super().__init__("ReportGeneratorAgent", context)
#         self.output_dir = output_dir
#         os.makedirs(output_dir, exist_ok=True)
#         self._init_pdf_settings()

#     def _init_pdf_settings(self):
#         """Initialize PDF settings with fallback fonts"""
#         try:
#             font_path = os.path.join("fonts", "DejaVuSans.ttf")
#             if os.path.exists(font_path):
#                 FPDF.add_font("DejaVu", "", font_path, uni=True)
#                 self.font_family = "DejaVu"
#             else:
#                 self.font_family = "Arial"
#         except:
#             self.font_family = "Helvetica"

#     def generate_pdf_report(self, vulnerabilities: List[Dict], filename: str) -> str:
#         """Generate PDF report using FPDF"""
#         full_path = os.path.join(self.output_dir, filename)
        
#         pdf = FPDF()
#         pdf.set_auto_page_break(auto=True, margin=15)
#         pdf.add_page()
        
#         # Header
#         pdf.set_font(self.font_family, 'B', 16)
#         pdf.cell(0, 10, "Smart Contract Audit Report", ln=True, align='C')
#         pdf.set_font(self.font_family, '', 12)
#         pdf.cell(0, 10, f"Contract: {self.read_context('contract_name', 'Unknown')}", ln=True)
#         pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
#         pdf.ln(10)

#         # Summary
#         pdf.set_font(self.font_family, 'B', 14)
#         pdf.cell(0, 10, "Risk Summary", ln=True)
#         pdf.set_font(self.font_family, '', 12)
#         pdf.multi_cell(0, 8, 
#             f"Risk Score: {self.read_context('overall_risk_score', 0)}/100\n"
#             f"Risk Level: {self.read_context('overall_risk_level', 'Unknown')}\n"
#             f"Vulnerabilities Found: {len(vulnerabilities)}",
#             ln=True)
#         pdf.ln(10)

#         # Findings
#         pdf.set_font(self.font_family, 'B', 14)
#         pdf.cell(0, 10, "Vulnerability Findings", ln=True)
        
#         if not vulnerabilities:
#             pdf.set_font(self.font_family, '', 12)
#             pdf.cell(0, 10, "No vulnerabilities found", ln=True)
#         else:
#             for idx, vuln in enumerate(vulnerabilities, 1):
#                 self._add_vulnerability_entry(pdf, idx, vuln)

#         # Footer
#         pdf.set_font(self.font_family, 'I', 8)
#         pdf.cell(0, 10, "Generated by DeFi Sentinel", ln=True, align='C')
        
#         pdf.output(full_path)
#         return full_path

#     def _add_vulnerability_entry(self, pdf: FPDF, index: int, vuln: Dict):
#         """Add a vulnerability entry to the PDF"""
#         pdf.set_font(self.font_family, 'B', 12)
#         pdf.cell(0, 8, f"{index}. {vuln['type']}", ln=True)
        
#         pdf.set_font(self.font_family, 'I', 10)
#         pdf.cell(0, 8, f"Severity: {vuln.get('severity', 'Unknown')}", ln=True)
        
#         pdf.set_font(self.font_family, '', 10)
#         pdf.multi_cell(0, 8, f"Location: {vuln.get('location', 'Unknown')}", ln=True)
#         pdf.multi_cell(0, 8, f"Description: {vuln.get('description', '')}", ln=True)
        
#         if 'code_snippet' in vuln:
#             pdf.set_font('Courier', '', 8)
#             pdf.multi_cell(0, 6, vuln['code_snippet'], ln=True)
#             pdf.set_font(self.font_family, '', 10)
        
#         if 'recommendation' in vuln:
#             pdf.set_font(self.font_family, 'B', 10)
#             pdf.multi_cell(0, 8, "Recommendation:", ln=True)
#             pdf.set_font(self.font_family, '', 10)
#             pdf.multi_cell(0, 8, vuln['recommendation'], ln=True)
        
#         pdf.ln(5)

#     def generate_json_report(self, vulnerabilities: List[Dict], filename: str) -> str:
#         """Generate JSON report"""
#         full_path = os.path.join(self.output_dir, filename)
        
#         report = {
#             "metadata": {
#                 "timestamp": datetime.now().isoformat(),
#                 "contract": self.read_context("contract_name", "Unknown"),
#                 "audit_version": "1.0"
#             },
#             "summary": {
#                 "risk_score": self.read_context("overall_risk_score", 0),
#                 "risk_level": self.read_context("overall_risk_level", "Unknown"),
#                 "vulnerabilities_count": len(vulnerabilities)
#             },
#             "findings": vulnerabilities,
#             "ai_analysis": self.read_context("ai_analysis", "")
#         }
        
#         with open(full_path, "w", encoding="utf-8") as f:
#             json.dump(report, f, indent=2, ensure_ascii=False)
            
#         return full_path

#     def run(self):
#         """Execute report generation"""
#         vulnerabilities = self.read_context("vulnerabilities", [])
#         contract_name = self.read_context("contract_name", "contract")
#         timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
#         pdf_path = self.generate_pdf_report(
#             vulnerabilities,
#             f"{contract_name}_report_{timestamp}.pdf"
#         )
#         json_path = self.generate_json_report(
#             vulnerabilities,
#             f"{contract_name}_report_{timestamp}.json"
#         )
        
#         self.write_context("pdf_report_path", pdf_path)
#         self.write_context("json_report_path", json_path)

import os
import json
from datetime import datetime
from fpdf import FPDF
from typing import List, Dict
from agents.base_agent import BaseAgent

class ReportGeneratorAgent(BaseAgent):
    def __init__(self, context, output_dir: str = "reports"):
        super().__init__("ReportGeneratorAgent", context)
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        self._init_pdf_settings()

    def _init_pdf_settings(self):
        try:
            font_path = os.path.join("fonts", "DejaVuSans.ttf")
            if os.path.exists(font_path):
                FPDF.add_font("DejaVu", "", font_path, uni=True)
                self.font_family = "DejaVu"
            else:
                self.font_family = "Arial"
        except:
            self.font_family = "Helvetica"

    def generate_pdf_report(self, vulnerabilities: List[Dict], filename: str) -> str:
        full_path = os.path.join(self.output_dir, filename)
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        pdf.set_font(self.font_family, 'B', 16)
        pdf.cell(0, 10, "Smart Contract Audit Report", ln=True, align='C')
        pdf.set_font(self.font_family, '', 12)
        pdf.cell(0, 10, f"Contract: {self.read_context('contract_name', 'Unknown')}", ln=True)
        pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
        pdf.ln(10)

        # Risk summary
        pdf.set_font(self.font_family, 'B', 14)
        pdf.cell(0, 10, "Risk Summary", ln=True)
        pdf.set_font(self.font_family, '', 12)
        pdf.multi_cell(0, 8, 
            f"Risk Score: {self.read_context('overall_risk_score', 0)}/100\n"
            f"Risk Level: {self.read_context('overall_risk_level', 'Unknown')}\n"
            f"Vulnerabilities Found: {len(vulnerabilities)}",
        )
        pdf.ln(10)

        # Vulnerabilities
        pdf.set_font(self.font_family, 'B', 14)
        pdf.cell(0, 10, "Vulnerability Findings", ln=True)
        if not vulnerabilities:
            pdf.set_font(self.font_family, '', 12)
            pdf.cell(0, 10, "No vulnerabilities found", ln=True)
        else:
            for idx, vuln in enumerate(vulnerabilities, 1):
                self._add_vulnerability_entry(pdf, idx, vuln)

        # AI Analysis
        ai_text = self.read_context("ai_analysis", "")
        if ai_text:
            pdf.set_font(self.font_family, 'B', 14)
            pdf.cell(0, 10, "AI-Powered Analysis", ln=True)
            pdf.set_font(self.font_family, '', 11)
            pdf.multi_cell(0, 8, ai_text)
            pdf.ln(5)

        pdf.set_font(self.font_family, 'I', 8)
        pdf.cell(0, 10, "Generated by DeFi Sentinel", ln=True, align='C')
        pdf.output(full_path)
        return full_path

    def _add_vulnerability_entry(self, pdf: FPDF, index: int, vuln: Dict):
        pdf.set_font(self.font_family, 'B', 12)
        pdf.cell(0, 8, f"{index}. {vuln['type']}", ln=True)
        pdf.set_font(self.font_family, 'I', 10)
        pdf.cell(0, 8, f"Severity: {vuln.get('severity', 'Unknown')}", ln=True)
        pdf.set_font(self.font_family, '', 10)
        pdf.multi_cell(0, 8, f"Location: {vuln.get('location', 'Unknown')}")
        pdf.multi_cell(0, 8, f"Description: {vuln.get('description', '')}")
        if 'recommendation' in vuln:
            pdf.set_font(self.font_family, 'B', 10)
            pdf.cell(0, 8, "Recommendation:", ln=True)
            pdf.set_font(self.font_family, '', 10)
            pdf.multi_cell(0, 8, vuln["recommendation"])
        pdf.ln(5)

    def generate_json_report(self, vulnerabilities: List[Dict], filename: str) -> str:
        full_path = os.path.join(self.output_dir, filename)
        report = {
            "metadata": {
                "timestamp": datetime.now().isoformat(),
                "contract": self.read_context("contract_name", "Unknown"),
                "audit_version": "1.0"
            },
            "summary": {
                "risk_score": self.read_context("overall_risk_score", 0),
                "risk_level": self.read_context("overall_risk_level", "Unknown"),
                "vulnerabilities_count": len(vulnerabilities)
            },
            "findings": vulnerabilities,
            "ai_analysis": self.read_context("ai_analysis", "")
        }
        with open(full_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        return full_path

    def run(self):
        vulnerabilities = self.read_context("vulnerabilities", [])
        contract_name = self.read_context("contract_name", "contract")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        pdf_path = self.generate_pdf_report(
            vulnerabilities, f"{contract_name}_report_{timestamp}.pdf"
        )
        json_path = self.generate_json_report(
            vulnerabilities, f"{contract_name}_report_{timestamp}.json"
        )

        self.write_context("pdf_report_path", pdf_path)
        self.write_context("json_report_path", json_path)
